services:
  kibana:
    image: "docker.elastic.co/kibana/kibana:${ES_VERSION}"
    container_name: "kibana"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "if curl -u elastic:${ELASTIC_PASSWORD} -fsS http://localhost:5601/api/status | grep -q '\"state\":\"green\"'; then echo '✅ Kibana is healthy'; exit 0; else echo '❌ Kibana not ready yet'; exit 1; fi"
        ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
