version: "3.8"

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}"
    container_name: "es-single"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ES_SECURITY}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "if curl -u elastic:${ELASTIC_PASSWORD} -fsS http://localhost:9200 >/dev/null; then echo '✅ Elasticsearch is healthy'; exit 0; else echo '❌ Elasticsearch not ready yet'; exit 1; fi"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  esdata:
