name: Custom CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # 3. Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build local distribution
      - name: Build local distribution
        run: ./gradlew localDistro --stacktrace --no-daemon

      # 5. Run unit  tests
      - name: Run server tests
        run: ./gradlew :server:test --stacktrace --no-daemon

      # 6. Upload all test reports
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-java-21
          path: |
            **/build/test-results/**/*
            **/build/reports/tests/**/*